function param = parameterInfo

% Copyright 2012 The MathWorks, Inc.

param = [...
  nnetParamInfo('regularization','Regularization Ratio','nntype.real_0_to_1',0,...
  'Fraction of performance associated with regularization.'),...
  nnetParamInfo('normalization','Normalization','nntype.error_norm_mode','none',...
  'The kind of error normalization relative to target ranges.'),...
  nnetParamInfo('eta1','Penalty Factor 1','nntype.num_scalar',0.1,...
  'Fraction of performance associated with regularization.'),...
  nnetParamInfo('eta2','Penalty Factor 2','nntype.num_scalar',0.1,...
  'Fraction of performance associated with regularization.'),...
  nnetParamInfo('beta','Penalty Factor 3','nntype.num_scalar',10,...
  'Fraction of performance associated with regularization.'),...
  ];
%   nnetParamInfo('erro_penalty_ratio','Error and Penalty Ratio','nntype.num_scalar',1,...
%   'Fraction of performance associated with regularization.'),...
%   ];
